## 데이터셋

http://ai.stanford.edu/~amaas/data/sentiment/



In [1]:
from sklearn.datasets import load_files

In [3]:
reviews_train = load_files("../data/text/classification_text/moview-review-aclImdb/train/")

### load_files 에 대해서

http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_files.html

레이블은 디렉토리 이름으로 정하고

디렉토리 안의 데이터를 적절해 셔플해서 로딩합니다.


영화 평가에 대한 분류는 긍정적(pos) 또는 부정적(neg) 로만 구분합니다.

In [5]:
reviews_train.target_names

['neg', 'pos']

In [6]:
text_train, y_train = reviews_train.data, reviews_train.target
print("type of text train: ", type(text_train))
print("lengh of text_train: ", len(text_train))

type of text train:  <class 'list'>
lengh of text_train:  25000


## 데이터 살펴보기

In [8]:
text_train[0]

b"Zero Day leads you to think, even re-think why two boys/young men would do what they did - commit mutual suicide via slaughtering their classmates. It captures what must be beyond a bizarre mode of being for two humans who have decided to withdraw from common civility in order to define their own/mutual world via coupled destruction.<br /><br />It is not a perfect movie but given what money/time the filmmaker and actors had - it is a remarkable product. In terms of explaining the motives and actions of the two young suicide/murderers it is better than 'Elephant' - in terms of being a film that gets under our 'rationalistic' skin it is a far, far better film than almost anything you are likely to see. <br /><br />Flawed but honest with a terrible honesty."

###  br / 제거

In [9]:
text_train = [text.replace(b"<br />", b" ") for text in text_train]

In [11]:
import numpy as np

In [13]:
np.bincount(y_train)

array([12500, 12500], dtype=int64)

## 테스트 데이터셋도 같은 방법으로 얻습니다.

In [14]:
reviews_test = load_files("../data/text/classification_text/moview-review-aclImdb/test/")

In [15]:
text_test, y_test = reviews_test.data, reviews_test.target

In [17]:
len(text_test)

25000

In [18]:
text_test[0]

b"Don't hate Heather Graham because she's beautiful, hate her because she's fun to watch in this movie. Like the hip clothing and funky surroundings, the actors in this flick work well together. Casey Affleck is hysterical and Heather Graham literally lights up the screen. The minor characters - Goran Visnjic {sigh} and Patricia Velazquez are as TALENTED as they are gorgeous. Congratulations Miramax & Director Lisa Krueger!"

In [20]:
type(text_test[0])

bytes

In [21]:
text_test = [text.replace(b"<br />", b" ") for text in text_test]

## Representing text data as Bag of Words

문장의 구조를 무시하고 단어가 몇 번 등장했는지에 대한 데이터만 모으는 방법입니다.

1) Tokenization: 공백이나 구두점으로 단어를 구분한다.

2) 모든 문서에 나오 단어를 모아서 번호를 붙인다.

3) Encoding: 각각의 문서에 대해서 각각의 단어들이 얼마나 등장했는 센다.


모든 문서에 등장하는 단어가 총 100 개라면  길이가 100 인 벡터를 만듭니다.  [ 0 0 0 ... 0 ]

모은 문장에 들어있는 단어의 출현 여부를 이 벡터로 표현할 수 있습니다.


In [22]:
bards_words =["The fool doth think he is wise,",
              "but the wise man knows himself to be a fool"]

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

In [24]:
vect = CountVectorizer().fit(bards_words)

In [25]:
vect

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

### CountVector 가 하는 일

단어를  "\b\w\w+\b" 로 추출합니다. 즉 길이가 2 이상인 문자를 고릅니다.

그리고 단어를 모두 소문자로 바꿉니다.

In [27]:
print(vect.vocabulary_)

{'the': 9, 'fool': 3, 'doth': 2, 'think': 10, 'he': 4, 'is': 6, 'wise': 12, 'but': 1, 'man': 8, 'knows': 7, 'himself': 5, 'to': 11, 'be': 0}


In [28]:
vect.stop_words_

set()

In [31]:
bag_of_words = vect.transform(bards_words)
bag_of_words , type(bag_of_words)

(<2x13 sparse matrix of type '<class 'numpy.int64'>'
 	with 16 stored elements in Compressed Sparse Row format>,
 scipy.sparse.csr.csr_matrix)

In [32]:
bag_of_words.toarray()

array([[0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1],
       [1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1]], dtype=int64)

## Bag-of-word for movie reviews


In [33]:
vect = CountVectorizer().fit(text_train)
x_train = vect.transform(text_train)
print(repr(x_train))

<25000x74849 sparse matrix of type '<class 'numpy.int64'>'
	with 3431196 stored elements in Compressed Sparse Row format>


2.5 만 개의 샘플,  74849 개의 단어

In [34]:
feature_names = vect.get_feature_names()
print(len(feature_names))

print(feature_names[:20])

74849
['00', '000', '0000000000001', '00001', '00015', '000s', '001', '003830', '006', '007', '0079', '0080', '0083', '0093638', '00am', '00pm', '00s', '01', '01pm', '02']


In [35]:
print(feature_names[20010:20030])

['dratted', 'draub', 'draught', 'draughts', 'draughtswoman', 'draw', 'drawback', 'drawbacks', 'drawer', 'drawers', 'drawing', 'drawings', 'drawl', 'drawled', 'drawling', 'drawn', 'draws', 'draza', 'dre', 'drea']


### 불필요한 단어들...

영화 평가와는 상관없는(예: 숫자) 단어들이 많이 포함되어 있지만 우선 이대로 우선 분류를 해보겠습니다.

In [36]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

scores = cross_val_score(LogisticRegression(), x_train, y_train, cv=5)
print(scores)
np.mean(scores)

[ 0.8824  0.876   0.8822  0.8884  0.8776]


0.88131999999999999

### 이상태로 GridSearch 를 사용해서 간단한 파라미터 튜닝

In [37]:
from sklearn.model_selection import GridSearchCV

param_grid = {'C':[0.001, 0.01, 0.1, 1, 10]}

grid = GridSearchCV(LogisticRegression(), param_grid, cv=5)
grid.fit(x_train, y_train)
print("Best cross-validation socre: ", grid.best_score_)
print("Best parameters: ", grid.best_params_)

Best cross-validation socre:  0.88816
Best parameters:  {'C': 0.1}


score 가 조금 향상되었습니다.

best param 으로 테스트 셋을 평가해보면 아래와  같습니다.

In [38]:
x_test = vect.transform(text_test)
grid.score(x_test, y_test)

0.87892000000000003

## 개선1,  최소 n 번 이상나온 단어만 사용



In [40]:
vect = CountVectorizer(min_df=5).fit(text_train)
x_train = vect.transform(text_train)
print(repr(x_train))

<25000x27271 sparse matrix of type '<class 'numpy.int64'>'
	with 3354014 stored elements in Compressed Sparse Row format>


이번에는 최소 5 번 이상 등장한 단어만 추출해서 2.7만개의 단어만 사용했습니다.


In [41]:
feature_names = vect.get_feature_names()
feature_names[::700]

['00',
 'affections',
 'appropriately',
 'barbra',
 'blurbs',
 'butchered',
 'cheese',
 'commitment',
 'courts',
 'deconstructed',
 'disgraceful',
 'dvds',
 'eschews',
 'fell',
 'freezer',
 'goriest',
 'hauser',
 'hungary',
 'insinuate',
 'juggle',
 'leering',
 'maelstrom',
 'messiah',
 'music',
 'occasional',
 'parking',
 'pleasantville',
 'pronunciation',
 'recipient',
 'reviews',
 'sas',
 'shea',
 'sneers',
 'steiger',
 'swastika',
 'thrusting',
 'tvs',
 'vampyre',
 'westerns']

In [44]:
param_grid

{'C': [0.001, 0.01, 0.1, 1, 10]}

In [47]:
scores = cross_val_score(LogisticRegression(), x_train, y_train, cv=5)
print(scores)
np.mean(scores)

[ 0.8798  0.8736  0.8812  0.886   0.8758]


0.87927999999999995

In [48]:
grid = GridSearchCV(LogisticRegression(), param_grid, cv=5)
grid.fit(x_train, y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'C': [0.001, 0.01, 0.1, 1, 10]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=0)

In [49]:
print("Best cv score: ", grid.best_score_)

Best cv score:  0.88812
