CNN Convolution Neural Network는 신경망의 단점이라고 할 수 있는 '층이 늘어나면 제대로 학습하지 못한다'라는 문제를 입력층과 출력층 사이에 합성곱층과 풀링층을 넣어 보완한 것입니다.

이번 실습에서는 Caltech 101 데이터 중에서 5가지 종류의 카테고리를 분류해보겠습니다.

각 카테고리당 이미지가 60장 정도 있고 총 337 장의 사진으로 훈련을 시킵니다.



### 이미지 데이터를 가공해서 파이썬 데이터로 변환하기

이미지를 일정한 크기로 리사이즈하고 24비트 RGB 형식으로 변환해 둡니다.

In [1]:
from PIL import Image
import os, glob
import numpy as np
from sklearn.model_selection import train_test_split


In [2]:
caltech_dir = '../data/image/101_ObjectCategories'
categories = ['chair', 'camera', 'butterfly','elephant','flamingo']
nb_classes = len(categories)

image_w = 64
image_h = 64
pixels = image_w * image_h * 3

#이미지 데이터 읽어 들이기

X = []
Y = []
for idx, cat in enumerate(categories):
    label = [0 for i in range(len(categories)) ]
    label[idx] = 1
    
    image_dir = caltech_dir + '/' + cat
    files = glob.glob(image_dir+'/*.jpg')
    for i, f in enumerate(files):
        img = Image.open(f)
        img = img.convert('RGB')
        img = img.resize((image_w, image_h))
        data = np.asarray(img)
        X.append(data)
        Y.append(label)
        if i % 10 == 0:
            print(i, '\n', data)

X = np.array(X)            
Y = np.array(Y)

X_train, X_test, y_train, y_test = train_test_split(X, Y)

xy = (X_train, X_test, y_train, y_test)
np.save('../data/image/5obj.npy', xy)

print('ok,', len(Y))
        
    

0 
 [[[255 250 251]
  [255 253 255]
  [254 253 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[254 255 255]
  [255 252 246]
  [255 254 243]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[239 245 245]
  [129 113  88]
  [156 131  91]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ..., 
 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
10 
 [[[207 187 188]
  [208 188 189]
  [206 186 185]
  ..., 
  [203 179 153]
  [201 177 151]
  [200 176 150]]

 [[208 188 187]
  [206 186 185]
  [209 190 186]
  ..., 
  [208 184 158]
  [204 180 154]
  [202 178 152]]

 [[204 185 181]
  [204 185 179]
  [204 185 179]
  ..., 
  [207 183 157]
  [203 179 153]
  [202 178 152]]

 ..., 
 [[233 220 212]
  [232 

30 
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [254 251 255]
  [255 255 246]
  [ 91 103 125]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [254 251 255]
  [255 255 246]
  [ 91 103 125]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ..., 
  [254 251 255]
  [255 255 246]
  [ 91 103 125]]

 ..., 
 [[ 61 153  68]
  [ 19 143  49]
  [255 225 253]
  ..., 
  [ 67  67  77]
  [153 155 144]
  [ 83  95 117]]

 [[222 255 242]
  [240 255 255]
  [235 247 247]
  ..., 
  [ 73  74  68]
  [209 215 213]
  [ 88 107 124]]

 [[117 143 166]
  [123 144 171]
  [130 147 177]
  ..., 
  [119 131 157]
  [130 144 171]
  [119 138 178]]]
40 
 [[[243 226   0]
  [243 226   0]
  [242 225   0]
  ..., 
  [236 215   0]
  [235 214   0]
  [237 216   1]]

 [[243 226   0]
  [243 226   0]
  [242 225   0]
  ..., 
  [236 215   0]
  [235 214   0]
  [237 216   1]]

 [[242 225   0]
  [242 225   0]
  [244 227   0]
  ..., 
  [236 215   0]
  [236 215   0]
  [236 215   0]]

 ..., 
 [[  0   0   0]
  [  0

10 
 [[[226 185 189]
  [232 193 196]
  [237 203 204]
  ..., 
  [104 155  89]
  [111 159 101]
  [104 153  88]]

 [[209 163 163]
  [211 167 166]
  [219 178 176]
  ..., 
  [100 152  88]
  [103 153  92]
  [ 99 150  83]]

 [[215 161 159]
  [210 159 156]
  [208 159 155]
  ..., 
  [ 95 151  78]
  [ 92 144  80]
  [ 96 149  79]]

 ..., 
 [[ 64 122  46]
  [ 54 109  41]
  [ 75 126  67]
  ..., 
  [113 153 103]
  [ 47 101  26]
  [ 82 135  63]]

 [[ 62 121  53]
  [ 50 106  43]
  [ 56 109  53]
  ..., 
  [ 94 142  90]
  [ 48 101  31]
  [103 156  86]]

 [[ 76 135  77]
  [ 60 119  63]
  [ 70 125  70]
  ..., 
  [ 53 108  50]
  [ 83 139  78]
  [ 61 117  56]]]
20 
 [[[246 255 255]
  [255 249 253]
  [254 255 253]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 251 242]
  [250 253 255]
  [240 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 253]
  [251 251 249]
  [248 255 248]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ..., 
 [[255 255 255]
  [255

In [6]:
from keras.models import Sequential
from keras.layers import Convolution2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
import numpy as np

In [7]:
categories = ['chair', 'camera', 'butterfly','elephant','flamingo']
nb_classes = len(categories)

image_w = 64
image_h = 64

X_train, X_test, y_train, y_test = np.load('../data/image/5obj.npy')

X_train = X_train.astype(float) / 256
X_test = X_test.astype(float) / 256

model = Sequential()
model.add(Convolution2D(32, 3, 3,
                       border_mode='same',
                       input_shape=X_train.shape[1:]))

model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Convolution2D(32, 3, 3, border_mode='same'))
                       

model.add(Activation('relu'))
model.add(Convolution2D(64,3,3))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.25))
model.add(Dense(nb_classes))
model.add(Activation('softmax'))

model.compile(loss='binary_crossentropy',
             optimizer='rmsprop',
             metrics=['accuracy'])

model.fit(X_train, y_train, batch_size=32, nb_epoch=50)

score = model.evaluate(X_test, y_test)
print('loss=', score[0])
print('accuracy=', score[1])



C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(64, 64, 3..., padding="same")`
  from ipykernel import kernelapp as app
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), padding="same")`
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3))`
C:\ProgramData\Anaconda3\lib\site-packages\keras\models.py:848: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/50
250/250 [==============================] - 13s - loss: 3.5154 - acc: 0.6856    
Epoch 2/50
250/250 [==============================] - 10s - loss: 5.2323 - acc: 0.6736    
Epoch 3/50
250/250 [==============================] - 11s - loss: 5.1611 - acc: 0.6672    
Epoch 4/50
250/250 [==============================] - 11s - loss: 2.6619 - acc: 0.7024    
Epoch 5/50
250/250 [==============================] - 12s - loss: 0.5445 - acc: 0.7768    
Epoch 6/50
250/250 [==============================] - 12s - loss: 0.4423 - acc: 0.8064    
Epoch 7/50
250/250 [==============================] - 12s - loss: 0.4184 - acc: 0.8168    
Epoch 8/50
250/250 [==============================] - 11s - loss: 0.4029 - acc: 0.8288    
Epoch 9/50
250/250 [==============================] - 11s - loss: 0.4121 - acc: 0.8264    
Epoch 10/50
250/250 [==============================] - 11s - loss: 0.3607 - acc: 0.8568    
Epoch 11/50
250/250 [==============================] - 12s - loss: 0.3812 - acc: 0.8664  